# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_id', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_posts', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_follows', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_followed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('post_url', models.CharField(blank=True, max_length=400, null=True)),
                ('post_image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('post_category', models.CharField(blank=True, max_length=200, null=True)),
                ('post_comments', models.CharField(blank=True, max_length=200, null=True)),
                ('post_likes', models.CharField(blank=True, max_length=200, null=True)),
                ('post_location', models.CharField(blank=True, max_length=200, null=True)),
                ('post_caption', models.TextField(blank=True, null=True)),
                ('engagement_rate', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
